import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Card from "../widgets/homepage/components/Card";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DFA Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex flex-wrap items-streth gap-4">
          {Array.from({ length: 50 }).map((data, index) => (
            <Card
              data={{
                level: 3,
                partnersNumber: 133,
              }}
              isActive={index === 0}
              users={Array.from({ length: 20 })}
              key={index}
            />
          ))}
        </div>
      </Layout>
    </>
  );
};

export default Home;
