import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Homepage from "../widgets/homepage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DFA Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Homepage />
      </Layout>
    </>
  );
};

export default Home;
